import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { proposalsTable, clientsTable } from "@workspace/db/schema";
import { eq, sql } from "drizzle-orm";

const router: IRouter = Router();

// ── Default boilerplate text for new proposals ────────────────────────
const BOILERPLATE_DEFAULTS = {
  changeOrders: "Any work requested by the client that is outside the original scope of work must be documented and approved in writing before the additional work is performed. Change orders may affect pricing, material needs, and project duration.",
  siteConditions: "This proposal is based on visible conditions at the time of the estimate. We are not responsible for hidden or concealed conditions including structural deficiencies, water damage, code violations, pest damage, mold, rot, deteriorated framing, outdated utilities, or inaccessible systems discovered after work begins. Any such conditions will be brought to the client's attention and may require additional work and cost.",
  materials: "Materials will be installed as specified in the proposal or based on approved selections. If a specified material becomes unavailable, a comparable substitute may be recommended for client approval. Delays caused by backorders, discontinued products, or supplier issues may impact the project timeline.",
  permits: "Unless explicitly stated otherwise, permits, plans, engineering, and municipal approvals are excluded from this proposal. Work will be performed in accordance with standard trade practices; however, any required upgrades related to code compliance discovered during the project may result in additional charges if not included in the original scope.",
  access: "The client agrees to provide reasonable access to the work area during normal working hours and to ensure that water, electricity, and any other necessary utilities are available unless otherwise agreed. The work area should be reasonably cleared of personal items, furniture, valuables, and obstacles prior to the start of work.",
  cleanup: "Basic jobsite cleanup is included unless otherwise stated. This includes removal of construction debris generated by our work from active work areas. Deep cleaning, specialized disposal, hazardous waste handling, and off-site hauling beyond standard debris removal are excluded unless specifically listed in the proposal.",
  warranty: "We warrant our workmanship for a period of one (1) year from the date of substantial completion, covering defects caused by installation or labor performed by our company under normal use conditions. This warranty does not cover owner abuse, misuse, neglect, manufacturer defects, normal wear and tear, or damage caused by third parties or conditions outside our control.",
  cancellation: "Deposits may be non-refundable once scheduling, material ordering, fabrication, or mobilization has begun. If the client cancels the project after acceptance and before completion, the client agrees to pay for work performed, materials ordered, restocking fees, and any costs incurred up to the cancellation date.",
  liability: "Our liability under this proposal shall be limited to the value of the contracted work actually performed. We shall not be liable for incidental, indirect, special, or consequential damages, delays outside our control, or pre-existing conditions not caused by our work.",
};

async function nextProposalNumber(): Promise<string> {
  const rows = await db
    .select({ num: proposalsTable.proposalNumber })
    .from(proposalsTable)
    .orderBy(sql`LENGTH(proposal_number) DESC, proposal_number DESC`)
    .limit(1);
  if (!rows.length) return "PROP-0001";
  const last = parseInt(rows[0].num.replace("PROP-", ""), 10);
  return `PROP-${String(last + 1).padStart(4, "0")}`;
}

function fmt(p: typeof proposalsTable.$inferSelect & { clientName?: string | null }) {
  return { ...p, clientName: p.clientName ?? null, createdAt: p.createdAt.toISOString() };
}

// ── List ──────────────────────────────────────────────────────────────
router.get("/proposals", async (_req, res) => {
  const rows = await db
    .select({
      id: proposalsTable.id,
      proposalNumber: proposalsTable.proposalNumber,
      clientId: proposalsTable.clientId,
      clientName: clientsTable.name,
      projectName: proposalsTable.projectName,
      status: proposalsTable.status,
      validUntil: proposalsTable.validUntil,
      createdAt: proposalsTable.createdAt,
    })
    .from(proposalsTable)
    .leftJoin(clientsTable, eq(proposalsTable.clientId, clientsTable.id))
    .orderBy(sql`${proposalsTable.createdAt} DESC`);
  res.json(rows.map(r => ({ ...r, clientName: r.clientName ?? null, createdAt: r.createdAt.toISOString() })));
});

// ── Create ────────────────────────────────────────────────────────────
router.post("/proposals", async (req, res) => {
  const {
    clientId, projectName, status,
    introText, projectOverview, scopeOfWork, exclusions, allowances,
    deliverables, timeline, paymentTerms,
    changeOrders, siteConditions, materials, permits, access, cleanup,
    warranty, cancellation, liability,
    terms, notes, validUntil,
  } = req.body;

  const proposalNumber = await nextProposalNumber();
  const [proposal] = await db.insert(proposalsTable).values({
    proposalNumber,
    clientId: clientId || null,
    projectName,
    status: status || "draft",
    introText: introText || null,
    projectOverview: projectOverview || null,
    scopeOfWork: scopeOfWork || null,
    exclusions: exclusions || null,
    allowances: allowances || null,
    deliverables: deliverables || null,
    timeline: timeline || null,
    paymentTerms: paymentTerms || null,
    // Pre-fill boilerplate defaults if not provided
    changeOrders: changeOrders || BOILERPLATE_DEFAULTS.changeOrders,
    siteConditions: siteConditions || BOILERPLATE_DEFAULTS.siteConditions,
    materials: materials || BOILERPLATE_DEFAULTS.materials,
    permits: permits || BOILERPLATE_DEFAULTS.permits,
    access: access || BOILERPLATE_DEFAULTS.access,
    cleanup: cleanup || BOILERPLATE_DEFAULTS.cleanup,
    warranty: warranty || BOILERPLATE_DEFAULTS.warranty,
    cancellation: cancellation || BOILERPLATE_DEFAULTS.cancellation,
    liability: liability || BOILERPLATE_DEFAULTS.liability,
    terms: terms || null,
    notes: notes || null,
    validUntil: validUntil || null,
  }).returning();

  const client = proposal.clientId
    ? await db.select({ name: clientsTable.name }).from(clientsTable).where(eq(clientsTable.id, proposal.clientId)).then(r => r[0])
    : null;

  res.status(201).json(fmt({ ...proposal, clientName: client?.name ?? null }));
});

// ── Get one ───────────────────────────────────────────────────────────
router.get("/proposals/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  const [row] = await db
    .select({
      id: proposalsTable.id,
      proposalNumber: proposalsTable.proposalNumber,
      clientId: proposalsTable.clientId,
      clientName: clientsTable.name,
      projectName: proposalsTable.projectName,
      status: proposalsTable.status,
      introText: proposalsTable.introText,
      projectOverview: proposalsTable.projectOverview,
      scopeOfWork: proposalsTable.scopeOfWork,
      exclusions: proposalsTable.exclusions,
      allowances: proposalsTable.allowances,
      deliverables: proposalsTable.deliverables,
      timeline: proposalsTable.timeline,
      paymentTerms: proposalsTable.paymentTerms,
      changeOrders: proposalsTable.changeOrders,
      siteConditions: proposalsTable.siteConditions,
      materials: proposalsTable.materials,
      permits: proposalsTable.permits,
      access: proposalsTable.access,
      cleanup: proposalsTable.cleanup,
      warranty: proposalsTable.warranty,
      cancellation: proposalsTable.cancellation,
      liability: proposalsTable.liability,
      terms: proposalsTable.terms,
      notes: proposalsTable.notes,
      validUntil: proposalsTable.validUntil,
      createdAt: proposalsTable.createdAt,
    })
    .from(proposalsTable)
    .leftJoin(clientsTable, eq(proposalsTable.clientId, clientsTable.id))
    .where(eq(proposalsTable.id, id));
  if (!row) return res.status(404).json({ error: "Proposal not found" });
  res.json(fmt({ ...row, clientName: row.clientName ?? null }));
});

// ── Update ────────────────────────────────────────────────────────────
router.put("/proposals/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  const {
    clientId, projectName, status, validUntil,
    introText, projectOverview, scopeOfWork, exclusions, allowances,
    deliverables, timeline, paymentTerms,
    changeOrders, siteConditions, materials, permits, access, cleanup,
    warranty, cancellation, liability,
    terms, notes,
  } = req.body;

  const set: Record<string, unknown> = {};
  if (clientId     !== undefined) set.clientId     = clientId || null;
  if (projectName  !== undefined) set.projectName  = projectName;
  if (status       !== undefined) set.status       = status;
  if (validUntil   !== undefined) set.validUntil   = validUntil || null;
  if (introText    !== undefined) set.introText    = introText || null;
  if (projectOverview !== undefined) set.projectOverview = projectOverview || null;
  if (scopeOfWork  !== undefined) set.scopeOfWork  = scopeOfWork || null;
  if (exclusions   !== undefined) set.exclusions   = exclusions || null;
  if (allowances   !== undefined) set.allowances   = allowances || null;
  if (deliverables !== undefined) set.deliverables = deliverables || null;
  if (timeline     !== undefined) set.timeline     = timeline || null;
  if (paymentTerms !== undefined) set.paymentTerms = paymentTerms || null;
  if (changeOrders !== undefined) set.changeOrders = changeOrders || null;
  if (siteConditions !== undefined) set.siteConditions = siteConditions || null;
  if (materials    !== undefined) set.materials    = materials || null;
  if (permits      !== undefined) set.permits      = permits || null;
  if (access       !== undefined) set.access       = access || null;
  if (cleanup      !== undefined) set.cleanup      = cleanup || null;
  if (warranty     !== undefined) set.warranty     = warranty || null;
  if (cancellation !== undefined) set.cancellation = cancellation || null;
  if (liability    !== undefined) set.liability    = liability || null;
  if (terms        !== undefined) set.terms        = terms || null;
  if (notes        !== undefined) set.notes        = notes || null;

  const [proposal] = await db.update(proposalsTable)
    .set(set as Partial<typeof proposalsTable.$inferInsert>)
    .where(eq(proposalsTable.id, id))
    .returning();
  if (!proposal) return res.status(404).json({ error: "Proposal not found" });

  const client = proposal.clientId
    ? await db.select({ name: clientsTable.name }).from(clientsTable).where(eq(clientsTable.id, proposal.clientId)).then(r => r[0])
    : null;

  res.json(fmt({ ...proposal, clientName: client?.name ?? null }));
});

// ── Delete ────────────────────────────────────────────────────────────
router.delete("/proposals/:id", async (req, res) => {
  const id = parseInt(req.params.id);
  await db.delete(proposalsTable).where(eq(proposalsTable.id, id));
  res.status(204).send();
});

export default router;
